services:
  socksco-app:
    build: ./SocksCo
    ports:
    - "8082:8080"
  watchco-app:
    build: ./WatchCo
    ports:
      - "8083:8080"
  amazingco-app:
    build: ./AmazingCo
    ports:
      - "8084:8080"